module.exports={
    PRODUCT_COLLECTION:'product',
    USER_COLLECTION:'user',
    ADMIN_COLLECTION:"admin",
    CATEGORY_COLLECTION:"category",
    COLOR_COLLECTION:"color",
    CART_COLLECTION:"cart",
    ORDER_COLLECTION:"order"
}