module.exports={
    PRODUCT_COLLECTION:'product',
    USER_COLLECTION:'user',
    ADMIN_COLLECTION:"admin",
    CATEGORY_COLLECTION:"category",
    COLOR_COLLECTION:"color",
    CART_COLLECTION:"cart",
    ORDER_COLLECTION:"order",
    DELIVERED_COLLECTION:'delivered',
    WISHLIST_COLLECTION:'wishlist',
    PRODUCT_OFFER:'productoffer',
    CATOFFER_COLLECTION:'catoffer',
    COUPON_COLLECTION:'coupon',
    USED_COUPON_COLLECTION:'used_coupon'
}